"""add numero_estudiante to students

Revision ID: 82bb1039606f
Revises: 
Create Date: 2026-02-11 18:12:54.799923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bb1039606f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('numero_estudiante', sa.String(), nullable=False))
    op.create_index(op.f('ix_students_numero_estudiante'), 'students', ['numero_estudiante'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_numero_estudiante'), table_name='students')
    op.drop_column('students', 'numero_estudiante')
    # ### end Alembic commands ###
